TSK-960: move for issues
hcengineering/anticrm pull request #2846
Opened 2023-03-28 14:15 UTC by ThetaDR

# Contribution checklist

## Brief description
https://front.hc.engineering/workbench/platform/tracker/TSK-960
## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

2023-03-28 14:52 UTC, BykhovDenis requested changes

2023-03-28 14:52 UTC, BykhovDenis commented on plugins/tracker-resources/src/components/issues/Move.svelte
> +  $: _class && translate(_class, {}).then((res) => (classLabel = res.toLocaleLowerCase()))
We already know class and class name I think

2023-03-28 14:52 UTC, BykhovDenis commented on plugins/tracker-resources/src/components/issues/Move.svelte
> +  async function invokeValidate (
We don't have object validator for issue, and I think won't have in observable future

2023-03-28 14:52 UTC, BykhovDenis commented on plugins/tracker-resources/src/utils.ts
> +  await client.update(doc, {
Let's do it all in one applyTx

2023-03-29 04:29 UTC, haiodo commented on plugins/tracker-resources/src/utils.ts
> +        if (name === 'subIssues') {
I would recommend to check for collection type is ref to class derived from Issue, so this code will not depend on text constant. Thanks.

2023-03-29 04:29 UTC, haiodo approved these changes

2023-03-29 13:04 UTC, BykhovDenis approved these changes

2023-03-29 13:04 UTC, merged